### ISSUE TITLE
QualifiedTypeIdentifier is flipped

### ISSUE THREAD

**Issue by thejameskyle** [babel/babylon#455]
### Input Code

```js
type b = a.b;
```

### Expected Behavior

```yaml
- type: QualifiedTypeIdentifier
  id: Identifier(a)
  qualification: Identifier(b)
```

### Current Behavior

```yaml
- type: QualifiedTypeIdentifier
  id: Identifier(b) # << flipped
  qualification: Identifier(a) # << flipped
```
